version: 2
updates:
  - package-ecosystem: "deno"
    directories:
      - "/e2e/scripts"
      - "/infra-architecture/scripts"
      - "/mountain-weather/scripts"
      - "/ja-tech-proofread/scripts"
    schedule:
      interval: "weekly"
