/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * E2E テスト試験項目書。
 */
export interface Spec {
  /**
   * テスト項目書のタイトル。
   */
  title: string;
  /**
   * テスト概要。目的、対象機能、前提条件等。
   */
  description?: string;
  /**
   * デバイスプリセット定義。キーはデバイス名（例: pc, mobile）。step で <device> 列参照と合わせて使用する。
   */
  devices?: {
    [k: string]: {
      viewport?: {
        width: number;
        height: number;
      };
      isMobile?: boolean;
      hasTouch?: boolean;
      userAgent?: string;
    };
  };
  case?: Case;
  /**
   * テストシナリオ一覧。
   */
  scenarios: Scenario[];
}
/**
 * テストケース。テストの条件パターンの総覧。
 */
export interface Case {
  /**
   * テーブルの列定義
   */
  columns: string[];
  /**
   * テストケースの各行。
   */
  rows: {
    [k: string]: string;
  }[];
}
/**
 * テストシナリオ。実際に確認する項目の一覧。
 */
export interface Scenario {
  /**
   * シナリオ名。
   */
  name: string;
  /**
   * シナリオの概要や検証内容。
   */
  description?: string;
  case?: Case;
  /**
   * テストステップ一覧。
   */
  steps: string[];
}
